import { ExpoConfig, ConfigContext } from "expo/config";
import { withGradleProperties, withDangerousMod, ConfigPlugin } from "expo/config-plugins";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import pkg from "./package.json";

// Bump the Gradle daemon heap so the D8 dex-merge step doesn't OOM merging the
// native-dep set (Expo modules, GoogleSignIn, Sentry, ...). android/ is
// regenerated by `expo prebuild --clean`, so this must be a config plugin that
// re-applies on every prebuild, not a hand-edit. (Carried over from the sibling
// Chewy Bytes apps.)
const GRADLE_JVMARGS = "-Xmx6144m -XX:MaxMetaspaceSize=1024m";

const withGradleHeap: ConfigPlugin = (config) =>
  withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === "org.gradle.jvmargs",
    );
    if (existing && existing.type === "property") {
      existing.value = GRADLE_JVMARGS;
    } else {
      cfg.modResults.push({ type: "property", key: "org.gradle.jvmargs", value: GRADLE_JVMARGS });
    }
    return cfg;
  });

// @react-native-google-signin pulls in AppCheckCore, a Swift pod depending on
// GoogleUtilities + RecaptchaInterop. Those don't ship module maps, so under the
// Expo SDK 56 static-library CocoaPods default `pod install` dies with "cannot
// yet be integrated as static libraries". Give them modular headers. ios/ is
// regenerated by prebuild, so this is a config plugin. (Carried over from CC.)
const MODULAR_HEADER_PODS = ["GoogleUtilities", "RecaptchaInterop"];
const withModularHeaders: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfilePath = join(cfg.modRequest.platformProjectRoot, "Podfile");
      let contents = readFileSync(podfilePath, "utf8");
      const marker = "use_expo_modules!";
      if (contents.includes(marker) && !contents.includes("# modular-headers")) {
        const lines = MODULAR_HEADER_PODS.map(
          (name) => `  pod '${name}', :modular_headers => true`,
        ).join("\n");
        contents = contents.replace(
          marker,
          `${marker}\n\n  # modular-headers: AppCheckCore (via GoogleSignIn) needs these as modules\n${lines}`,
        );
        writeFileSync(podfilePath, contents);
      }
      return cfg;
    },
  ]);

export default ({ config }: ConfigContext): ExpoConfig => {
  // Reverse the Google iOS Client ID (xxx.apps.googleusercontent.com →
  // com.googleusercontent.apps.xxx) for the CFBundleURLScheme.
  const googleIosClientId = process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID
    ? process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID.split(".").reverse().join(".")
    : "";

  // Per-variant identity: EXPO_PUBLIC_ENVIRONMENT (set per EAS profile) makes
  // dev/preview/prod produce DIFFERENT bundle ids + names so all three install
  // side-by-side. Matches the Chewy Bytes convention (chunkycrayon, gounbeaten).
  const env = process.env.EXPO_PUBLIC_ENVIRONMENT || "development";

  const appName =
    env === "production" ? "Outside IR35 Jobs" : env === "preview" ? "OIR35 Internal" : "OIR35 Dev";

  const bundleId =
    env === "production"
      ? "com.chewybytes.outsideir35.app"
      : env === "preview"
        ? "com.chewybytes.outsideir35.app.internal"
        : "com.chewybytes.outsideir35.app.dev";

  // Per-variant icons if present, else fall back to the prod icon (existsSync
  // guard means a missing badged icon never breaks a dev/preview build).
  const variantSuffix = env === "production" ? "" : env === "preview" ? "-preview" : "-dev";
  const pickIcon = (base: string): string => {
    const variantPath = `./assets/images/${base}${variantSuffix}.png`;
    return existsSync(join(__dirname, variantPath)) ? variantPath : `./assets/images/${base}.png`;
  };

  const expoConfig: ExpoConfig = {
    ...config,
    name: appName,
    slug: "outside-ir35-jobs",
    owner: "chewybytes",
    version: pkg.version,
    orientation: "portrait",
    icon: pickIcon("icon"),
    scheme: "outsideir35",
    userInterfaceStyle: "light",
    ios: {
      supportsTablet: true,
      bundleIdentifier: bundleId,
      infoPlist: {
        ITSAppUsesNonExemptEncryption: false,
        CFBundleURLTypes: [{ CFBundleURLSchemes: [googleIosClientId] }],
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: pickIcon("adaptive-icon"),
        backgroundColor: "#F6F5F3",
      },
      package: bundleId,
    },
    web: {
      bundler: "metro",
      output: "static",
      favicon: "./assets/images/favicon.png",
    },
    plugins: [
      "expo-router",
      [
        "expo-splash-screen",
        {
          image: "./assets/images/splash-icon.png",
          imageWidth: 200,
          resizeMode: "contain",
          backgroundColor: "#F6F5F3",
        },
      ],
      "expo-dev-client",
      "expo-font",
      "expo-web-browser",
      "expo-apple-authentication",
      "expo-secure-store",
      "expo-status-bar",
      "expo-image",
      "@react-native-google-signin/google-signin",
      [
        "@sentry/react-native",
        {
          url: "https://sentry.io/",
          project: "outside-ir35-jobs-app",
          organization: "chewybytes",
        },
      ],
      [
        "expo-build-properties",
        {
          android: { compileSdkVersion: 36, targetSdkVersion: 36, buildToolsVersion: "36.0.0" },
        },
      ],
    ],
    experiments: { typedRoutes: true },
    runtimeVersion: { policy: "appVersion" },
    // NOTE: set updates.url + extra.eas.projectId after `eas init` creates the
    // EAS project (one-time, needs the Expo account). Left unset so a local
    // `expo start` / prebuild works before the project exists.
  };

  return withModularHeaders(withGradleHeap(expoConfig)) as ExpoConfig;
};
